package source;

/**
* Connection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Connection.idl
* jeudi 15 janvier 2015 19 h 23 CEST
*/

public interface Connection extends ConnectionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Connection
