package source;

/**
* ConnectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Connection.idl
* jeudi 15 janvier 2015 19 h 23 CEST
*/

public final class ConnectionHolder implements org.omg.CORBA.portable.Streamable
{
  public Connection value = null;

  public ConnectionHolder ()
  {
  }

  public ConnectionHolder (Connection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConnectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConnectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConnectionHelper.type ();
  }

}
