package source;

/**
* EmitterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Emitter.idl
* jeudi 15 janvier 2015 19 h 23 CEST
*/

public interface EmitterOperations 
{
  void sendMessage (String to, String message);
} // interface EmitterOperations
