package source;

/**
* Emitter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Emitter.idl
* vendredi 27 septembre 2013 14 h 49 CEST
*/

public interface Emitter extends EmitterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Emitter
