package source;

/**
* EmitterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Emitter.idl
* jeudi 15 janvier 2015 19 h 23 CEST
*/

public final class EmitterHolder implements org.omg.CORBA.portable.Streamable
{
  public Emitter value = null;

  public EmitterHolder ()
  {
  }

  public EmitterHolder (Emitter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EmitterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EmitterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EmitterHelper.type ();
  }

}
