package source;

/**
* ReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Receiver.idl
* jeudi 15 janvier 2015 19 h 23 CEST
*/

public interface ReceiverOperations 
{
  void receive (String from, String message);
  void initClients (String[] clients);
  void addClient (String client);
  void remClient (String client);
} // interface ReceiverOperations
