package source;

/**
* Receiver.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Receiver.idl
* jeudi 15 janvier 2015 19 h 23 CEST
*/

public interface Receiver extends ReceiverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Receiver
