package source;

/**
* ReceiverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Receiver.idl
* jeudi 15 janvier 2015 19 h 23 CEST
*/

public final class ReceiverHolder implements org.omg.CORBA.portable.Streamable
{
  public Receiver value = null;

  public ReceiverHolder ()
  {
  }

  public ReceiverHolder (Receiver initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReceiverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReceiverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReceiverHelper.type ();
  }

}
